foo(5);
print("After error");
